### ISSUE TITLE
how to test ?

### ISSUE THREAD

**Issue by houguanqun** [IvoryCandy/super-resolution#2]

**Comment by houguanqun** [comment]
well , I have trained your model ,and I get some *.pth files,but I want to know how to test it, PLEASE!

**Comment by IvoryCandy** [comment]
Thanks for leaving this comment. I'm not sure what 'how to test' means here. If you wanna see the psnr score, there is a built-in `test()` function in each trainer. If you want to see how well the model perform on your custom pictures, go to see the super_resolve.py file.
