### ISSUE TITLE
Why use torch.manual_seed(self.seed)?

### ISSUE THREAD

**Issue by YongboLiang** [IvoryCandy/super-resolution#3]
Hi, may you tell me that why use `torch.manual_seed(self.seed)` in **build_model(self)**? And What is its role? Thank you!

**Comment by IvoryCandy** [comment]
Hi Yongbo,
Actually, [`manual_seed`](https://pytorch.org/docs/master/torch.html?highlight=manual_seed#torch.manual_seed) sets the random seed from pytorch random number generators, so it could keep the random initialization trackable and reproducible. 

p.s. there is a bug in seed settings and it is ineffective now, I will update those when available

**Comment by YongboLiang** [comment]
Thank you! I just see your reply now and I feel more understanding.
