### ISSUE TITLE
ModuleNotFoundError: No module named 'SRCNN'

### ISSUE THREAD

**Issue by kk6398** [IvoryCandy/super-resolution#31]
Dear, 
       I‘m a green hand in this field. When i wanna accomplish the "SRCNN" programmer, i click the "Run  'solver' ", but there is the mistake in my screen. As usual , if there occurs "ModuleNotFoundError: No module named XXX" , I would input"conda install XXX" in my terminal of cmd. However,  for this time ,i also do it again-----"conda install srcnn", it wasn't done. So i really need your help....
      Looking forward your answer.
                                                                                                                                                                    Sincerely.

**Comment by ZMingzhu** [comment]
hi, Do you deal with it? I have the same problem! Can you tell me how to solve this problem?Thank you!!
