### ISSUE TITLE
FSRCNN has color issue

### ISSUE THREAD

**Issue by Tiger1994** [IvoryCandy/super-resolution#4]
I am sorry to bother you, but I has a problem in using FSRCNN. The reconstructed SR images are tend to be gray image. If the FSRCNN can only reconstruct gray image, and why?
Thank you very much.

**Comment by IvoryCandy** [comment]
Thanks for mentioning this. Actually I don't know why right now. It might be relevant to the data preprocessing, which I convert pictures in `YCbCr` format and use `Y` as the only channel. I will look into it later this week.

**Comment by Tiger1994** [comment]
Thanks for your answer. I find the problem is caused by learning rate. I have tried a few of learning rates, the high learning rates (e.g. lr=0.01) can reconstruct color image, but the loss goes wild after dozens of epochs. And the low learning rates ( e.g. lr=0.0001) have the problem I mentioned before.
